apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP