apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: 0147896325/capstone-docker-image-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80